### ISSUE TITLE
ExpandRowColumn: disable toogle on click event on links and buttons

### ISSUE THREAD

**Issue by vyants** [kartik-v/yii2-grid#282]
Hello.

When enableRowClick = true, js catch all clicks on the row, including buttons and links.

Can you exclude this elements from click event?

**Comment by kartik-v** [comment]
Not implemented currently. You can individually do this on your elements via javascript. Probably will enhance later with an option when I get time.

**Comment by kartik-v** [comment]
Resolved via #284.

**Comment by kartik-v** [comment]
Ok this is resolved through following two options:

- One can add a CSS class `kv-disable-click` to any element in the row to disable row click.
- One can setup `rowClickExcludedTags` to disable specific tags... this defaults to `['A', 'BUTTON', 'INPUT']`.

**Comment by francislavoie** [comment]
This isn't fully solved. In Chrome v44, it seems that the target element when clicking on the pencil edit icon ends up being the `span` contained within the `a` tag. In this case, the toggle is still triggered.
